<?php
//Console debug output
//file_put_contents("php://stdout", sprintf("test")); 
function hello_theme() {
  return array(
    'hello_text' => array(
      'template' => 'hello-text',
      'variables' => array('text' => NULL)
    ),
    'event' => array(                                                                                             
     'render element' => 'elements',                                                                                    
     'file' => 'event.page.inc',                                                                                        
     'template' => 'event',                                                                                             
   ),
   'subscription' => array(                                                                                      
     'render element' => 'elements',                                                                                    
     'file' => 'subscription.page.inc',                                                                                 
     'template' => 'subscription',                                                                                      
   )
  );
}